# Generated by Django 3.1.2 on 2021-09-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingprice',
            new_name='shippingPrice',
        ),
    ]
