# Generated by Django 3.1.2 on 2021-09-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210912_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingPrice',
            new_name='shippinPrice',
        ),
    ]
