# Generated by Django 3.1.2 on 2021-09-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210912_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippinPrice',
            new_name='shippingPrice',
        ),
    ]
